name: Hugo Deploy (Update Site Documentation)

on:
  push:
    branches:
      - anthony-dardano
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0                            # Ensures git history is fully checked out
          ssh-known-hosts: github.com               # Needed to push to GitHub
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}   # Needed to push to GitHub
          submodules: true                          # Needed since Hugo theme is a submodule

      - name: Setup SSH
        run: |
          git config --global user.name "Anthony Dardano"
          git config --global user.email "anthony.dardano@gemini.com"
          git config --global gpg.format ssh
          git config --global commit.gpgsign true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Install Dependencies
        run: |
          go install github.com/gohugoio/hugo@latest
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

      - name: Setup Hugo
        run: |
          if which hugo >/dev/null 2>&1; then
            echo "Hugo already installed"
          else
            HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
            wget https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_${HUGO_VERSION#v}_Linux-64bit.tar.gz
            tar -xzf hugo_${HUGO_VERSION#v}_Linux-64bit.tar.gz
            sudo mv hugo $(go env GOPATH)/bin/
          fi

      - name: Build Site
        run: $(go env GOPATH)/bin/hugo -s hugo

      - name: Deploy Site
        run: |
          git checkout -b gh-pages
          make docs
          git add -A
          git commit -S -m "`Hugo`: Update Site (Documentation)" --signoff
          git push
