name: Go Module Release Tags

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0                            # Ensures git history is fully checked out
          ssh-known-hosts: github.com               # Needed to push to GitHub
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}   # Needed to push to GitHub
          submodules: true                          # Needed since Hugo theme is a submodule

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name "Anthony Dardano"
          git config --global user.email "anthony.dardano@gemini.com"
          git config --global user.signingkey ~/.ssh/id_ed25519
          git config --global gpg.format ssh
          git config --global commit.gpgsign true
          git config --global push.autoSetupRemote true
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Tag New Version
        run: |
          DATE_TIME=$(date -u +"%Y%m%d.%H%M%S")
          git tag $DATE_TIME
          git push origin $DATE_TIME
